image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.2.0-debian-12-r6

auth:
  username: 'tzkt'
  password: 'tzkt'
  database: 'tzkt_db'

primary:
  extraVolumes:
    - name: tzkt-snapshot-data
      emptyDir: {}

  extraVolumeMounts:
    - mountPath: "/tzkt-snapshot"
      name: "tzkt-snapshot-data"

  initdb:
    scripts:
      import_tzkt_snapshot: |
        #!/bin/sh
        PGPASSWORD="tzkt" psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE tzktdb TO tzkt;"
        PGPASSWORD="tzkt" pg_restore -c --if-exists -v -w -e -j 8 -U postgres -d tzktdb /tzkt-snapshot/tzkt-snapshot.backup
        PGPASSWORD="tzkt" psql -U postgres -d tzktdb -c "grant all privileges on all tables in schema public to tzkt;"
  persistence:
    size: '50Gi'
  networkPolicy:
    enabled: false
  initContainers:
    - name: tzkt-snapshot-downloader
      image: alpine:latest
      command: ["wget", "https://snapshots.tzkt.io/tzkt_v1.13_oxfordnet.backup", "-O", "/tzkt-snapshot/tzkt_db.backup"]
      volumeMounts:
        - mountPath: "/tzkt-snapshot"
          name: "tzkt-snapshot-data"